### DISCUSSION TITLE
Welcome to udiskie Discussions!

### DISCUSSION THREAD

**Discussion by coldfix** [coldfix/udiskie#211] [General]
## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

**Comment by ashish-kus** [comment]
I m bit confused, i am using hyprland on arch I changed some settings in ```~/.config/udiskie/config.yml``` and also added udiskie in execute once in hybrland ( which should execute udiskie when hyprland starts for the first time). Even after this udiskie dont work, it don't auto-mount drives, show no notification, don't have icon on system-tray etc. 
can anyone suggest me something. I will share my config here so that you can tell me if there is a problem.
```
#
# ~/.config/udiskie/config.yml
#

program_options:
  tray: true
  menu: flat
  automount: true
  notify: true
  password_prompt: ["gnome-keyring-query", "get", "{id_uuid}"]
  password_cache: 30
  file_manager: xdg-open
  # terminal: 'termite -d'
  # notify_command: "zenity --info --text '{event}: {device_presentation}'"
  notify_command: "zenity --info --text '{event}'"

notifications:
    # Use false, positive number or -1 (use default)
  timeout: -1
  # Above is global, below is specific.
  # device_mounted: 5
  # device_unmounted: false
  # device_added: false
  # device_removed: false
  # device_unlocked: -1
  # device_locked: -1
  job_failed: 5

    # Can be "all" too.
quickmenu_actions: [mount, unmount, unlock, terminal, detach, delete]

notification_actions:
  device_mounted:   [browse]
  device_added:     [mount]

icon_names:
  media: [drive-removable-media, media-optical]
  browse: [document-open, folder-open]
  terminal: [terminal, terminator, xfce-terminal]
  mount: [udiskie-mount]
  unmount: [udiskie-unmount]
  unlock: [udiskie-unlock]
  lock: [udiskie-lock]
  eject: [udiskie-eject, media-eject]
  detach: [udiskie-detach]
  delete: [udiskie-eject]
  quit: [application-exit]


```
