### DISCUSSION TITLE
Mount device with sync option

### DISCUSSION THREAD

**Discussion by semi710** [coldfix/udiskie#277] [Q&A]
How can i mount my usb devices using `sync` options?

**Comment by coldfix** [comment]
When mounting manually with `udiskie-mount` (assuming device is `sdb1`):

```bash
udiskie-mount /dev/sdb1 -o sync
```

Or, in order to set the sync option for auto-mounting, put this in your `$XDG_CONFIG_HOME/udiskie/config.yml` (usually `~/.config/udiskie/config.yml`):

```yaml
device_config:
 - id_uuid: 72145891-675a-46f9-8290-40ef748656dd
   options: [sync]
```

Where `id_uuid` should contain the filesystem UUID, which you can determine by looking at the output of `lsblk -o+uuid`
