### ISSUE TITLE
Make automount configurable

### ISSUE THREAD

**Issue by coldfix** [coldfix/udiskie#107]
I imagine a new config list `automount` similar to `mount_options` and `ignore_device`:

```
automount:
- device_file: /dev/sdb1
  auto: false
```

Maybe it's best to join these settings into one, e.g.:

```
device_config:
- device_file: /dev/sdb1
  ignore: false
  automount: false
  mount_options: ro
```
