### ISSUE TITLE
automounting works on one device, not on another

### ISSUE THREAD

**Issue by grawlinson** [coldfix/udiskie#141]
Contents of `~/.config/udiskie/config.yml`:
```
program_options:
  notify: false
device_config:
- id_uuid: a-valid-uuid-for-device-1
  keyfile: /etc/device-1.key
device_config:
- id_uuid: a-valid-uuid-for-device-2
  keyfile: /etc/device-2.key
```
When I plug in device 1, it automounts. When I try plugging in device 2, udiskie creates a gtk password prompt.

Manually entering `udiskie-mount /dev/device-2` successfully mounts the device without password prompt.
