### ISSUE TITLE
Action to open terminal

### ISSUE THREAD

**Issue by astronouth7303** [coldfix/udiskie#144]
Is it possible to add an additional action to open a terminal in the disk?

**Comment by coldfix** [comment]
Do you need the "Browse" entry? If not, you could adapt its setting in `~/.config/udiskie/config.yml`

```yaml
program_options:
  file_manager: open-terminal-at.sh
```

and add a `open-terminal-at.sh` executable like this in your PATH:

```sh
#! /bin/sh
cd "$1" && terminator
```

If you need both options, it's not currently possible. Although I could be persuaded to add something more customizable like this if you think it would be useful:

```
extra_actions:
- text: Open &Terminal
  command: ["urxvt", "-cd", "{mount_path}"]
  condition: ["is_filesystem", "is_mounted"]
```
