### ISSUE TITLE
Is there any way to disable the zenity window popup when inserting a usb device?

### ISSUE THREAD

**Issue by GijsTimmers** [coldfix/udiskie#154]
Running udiskie 1.5.1 on ubuntu 17.10 with i3 window manager.

Whenever I insert a usb device, I get two notifications:
- a `notify-send` message: 
```
    Device added
    device appeared on /dev/sdc
```
- a `zenity` message:
```
    Device mounted
    /dev/sdc1: <USB-ID> mounted on /media/user/<USB-ID>
    [Browse] [Cancel] [OK]
```

My `config.yml`:

```
program_options:
    tray: false
    automount: true
    notify: true
    file_manager: ranger
```

I'm not interested in the zenity message and want to disable that one. I read https://github.com/coldfix/udiskie/blob/master/doc/udiskie.8.txt but could not find how to do what I want. How can I get this done?
