### ISSUE TITLE
Trouble sourcing config file

### ISSUE THREAD

**Issue by Sponge5** [coldfix/udiskie#164]
Hi, I can't seem to make my udiskie work with my config file. I start it from my .xprofile. I tried both short and long options, relative and absolute paths and with/without parentheses.
File is ~/.config/udiskie/config.yml and looks like this: 
```
program options:
 # Configure defaults for command line options
 tray: true
 menu: nested
 automount: false
 notify: true
 file_manager: ranger

notifications:
 timeout: 1.5

notification_actions:
 device_mounted: [browse]
 device_added: [mount]
```
I don't have $XDG_CONFIG_HOME set to anything, is that the problem? I don't use xdg nor have it.
