### ISSUE TITLE
Automount selected LUKS device with globally disabled automount

### ISSUE THREAD

**Issue by marak8** [coldfix/udiskie#167]
With the following configuration udiskie automatically decrypts and mounts my LUKS device based on it's ID:
```
program_options:
  tray: true

device_config:
  - id_uuid: foobarbaz
    keyfile: /home/marek/keys/key1
```
I'd like to have automount disabled globally though and only mount selected devices, including regular filesystems and LUKS devices. With following configuration, udiskie leaves the LUKS device encrypted:
```
program_options:
  tray: true
  automount: false

device_config:
  - id_uuid: foobarbaz
    keyfile: /home/marek/keys/key1
    automount: true
```
I realize `automount` doesn't really fit here as dm device will be mounted in the end, but how should I specify that I want it to be automatically unlocked and mounted?

Thank you! Udiskie is great!

**Comment by coldfix** [comment]
Hey,

thanks for the feedback. This is currently not possible, but a very reasonable request. I wanted to change a few things about device rules in the next version anyway, but I can't promise that I have enough time to make it anytime soon. So any help is welcome in the meantime.

Best, Thomas

**Comment by coldfix** [comment]
Small update: I didn't think about this at the time of answering, but this is already available to some degree, although not dynamically changeable via the menu.

The trick is to append a catch-all rule in the `device_config` section:

```yaml
device_config:
  - id_uuid: foobarbaz
    keyfile: /home/marek/keys/key1
    automount: true

# matches all devices that are not matched by above rules:
- automount: false
```

I'm back on working on the next major update for udiskie and was thinking about this issue from a UI perspective. Do we still need an option to completely turn off automounting, even for configured devices? If so, then there are three states:

- fully disabled
- enabled, default=false
- enabled, default=true

Which is not so nice to add in the UI, so maybe it's better to drop the "fully disabled" state. What do you think?
