### ISSUE TITLE
Feature request - ability to ignore/filter snapd loop devices

### ISSUE THREAD

**Issue by alexenglish** [coldfix/udiskie#180]
On my Ubuntu 18.04 system (using i3wm rather than the normal interface, hence the use for udiskie), my list of devices is completely overwhelmed by the loop devices mounted by snapd. A way to ignore these and keep them from showing up would be fantastic.

These could be filtered by mount point, all of which are in subdirectories of /var/libs/snapd/snaps. An automatic filter or a way to create filters for which devices are shown would be fantastic.

Happy to provide whatever other details might be useful. Thank you.

**Comment by coldfix** [comment]
Hi,

sounds like a duplicate of #177. You can add a filter in your `~/.config/udiskie/config.yml`:

```yaml
device_config:
- id_type: squashfs
  ignore: true
```

or using the mount path from  `lsblk -lf`, e.g.:

```yaml
device_config:
- mount_path: /var/lib/snap/*
  ignore: true
- mount_path: /snap/*
  ignore: true
```

If you have an old version of udiskie, you may need to replace `device_config` by `ignore_device`.

Let me know which one works, I might add builtin rules as I have for docker, since this seems to be a more common problem then.

Best, Thomas
