### ISSUE TITLE
Mount option `compress=lzo' is not allowed

### ISSUE THREAD

**Issue by bookletchoir** [coldfix/udiskie#73]
I want to mount my external HDD formatted in btrfs with these options: ```rw, nosuid, nodev, noatime, compress=lzo, space_cache, autodefrag```

With this entry in ```/etc/fstab```, it works fine.
```
/dev/disk/by-uuid/d40cbab5-85a1-43de-96ce-06dbfe2fa70b /run/media/USER/external_hdd btrfs rw,nosuid,nodev,noatime,compress=lzo,space_cache,autodefrag 0 0
```

Result from ```/etc/mtab```
```
/dev/sdb1 /run/media/USER/external_hdd btrfs rw,nosuid,nodev,noatime,compress=lzo,space_cache,autodefrag 0 0
```

But, when I tries to use udiskie to mount it with the same options from config file, it doesn't seem to work properly
```bash
~ udiskie -c "$HOME/.config/udiskie/config.yml"
failed to mount /org/freedesktop/UDisks2/block_devices/sdb1: GDBus.Error:org.freedesktop.UDisks2.Error.OptionNotPermitted: Mount option `compress=lzo' is not allowed
```

Instead, it's mounted with (perhaps) default options.
Result from ```/etc/mtab```
```
/dev/sdb1 /run/media/USER/external_hdd btrfs rw,nosuid,nodev,relatime,space_cache 0 0
```

My config file in ```$HOME/.config/udiskie/config.yml```
```yaml
udisks_version: 2
tray: false
automount: false
notify: true
mount_options:
    - id_uuid: d40cbab5-85a1-43de-96ce-06dbfe2fa70b
      options: [rw, nosuid, nodev, noatime, compress=lzo, space_cache, autodefrag]
```

Am I missing something?
